### ISSUE TITLE
Timeline above the time slider

### ISSUE THREAD

**Issue by erictapen** [erictapen/mapping-migration#10]
We want to display total applications / amount of citizens for every selected COO/COA combination.

That timeline would be placed near the time slider.

We don't want to display axis for it. It should only provide a means to grasp the general temporal dynamic of the data faster.

![tmp pgL86H8Re9](https://user-images.githubusercontent.com/11532355/148093847-a1d6bc40-90f9-4204-a080-9091fda12df2.png)

**Comment by seragarez** [comment]
@herbertblb Maybe that's one point for "next steps" in the presentation? As I don't think we will have that until Tuesday. Or what do you say @erictapen ?

**Comment by erictapen** [comment]
Yeah I'm pretty sure that this feature won't make it into the webapp until tuesday.

**Comment by erictapen** [comment]
I provided a first implementation, mainly out of curiosity about the temporal dynamics to discover! Have fun.
