### ISSUE TITLE
position / farbcodes of footprints

### ISSUE THREAD

**Issue by herbertblb** [erictapen/mapping-migration#11]
work with the position as a very powerful tool
we could use position of footprints to enable comparison
maybe divide the background into 4 pieces where the footprints appear
or stay with the farbcodes, but change the colors

**Comment by seragarez** [comment]
Suggestion by Marian: different shapes / shoes for the footprints instead of color coding

**Comment by herbertblb** [comment]
>I realy like the visualization with the footprints!
I would suggest switsching the colours of "recognized" and "complementary protection". The orange apperas to me like the process is still in flux, because its simmilar to the red of "rejected"

**Comment by herbertblb** [comment]
Comment Gustav:
>For me its hard to differentiate the colors of the footprints. Maybe think about different icons to refine their meaning.
