### ISSUE TITLE
GDP or number of citizens?

### ISSUE THREAD

**Issue by erictapen** [erictapen/mapping-migration#13]
We have to decide on that quickly, as many places in the code depend on the decision.

**Comment by herbertblb** [comment]
comment Kalen:
>I might suggest using both or maybe more: Employment stats, Pop. growth, median income, political leadership, etc.

**Comment by herbertblb** [comment]
or add just some numbers as context

**Comment by erictapen** [comment]
@herbertblb @Findus2000 @yellowkobra @seragarez Könnt ihr mir nochmal auf die Sprünge helfen was hier der Stand war? Irgendwie ist mir fast so, als hätten wir das Ende letzter Sitzung auf Bewohner*innen festgemacht? Und wenn nicht hatten wir einen Entscheidungsprozess festgemacht?

**Comment by herbertblb** [comment]
@erictapen wir haben gerade nochmal darüber geredet und unser Ergebnis war, die Einwohner*innenzahl nach Friedas Vorschlag einzubeziehen und es dabei zu belassen. Also "pro 100.000 Einwohner*innen gab es 67 asylum decisions" und so weiter
