### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by herbertblb** [erictapen/mapping-migration#14]
title should give overview on what to expect

**Comment by erictapen** [comment]
My proposition here would be

> How do countries grant asylum?

Pros and cons imo:

- It answers the first questions people might ask themselves about the project: What answers does this offer to me?
- It somewhat diminishes our focus on the relevance of the COA in the asylum decision process.
- It's short.

**Comment by erictapen** [comment]
I think it would be good to have the title for the final course presentation.

**Comment by seragarez** [comment]
Hey @erictapen, we talked about this in our meeting today and decided to make the final decision together on Monday. Until then, we have a Frame for brainstorming on the title in Miro (on the left of the presentation slides), so we can all write down any new ideas that come to mind.

**Comment by seragarez** [comment]
**Sind wir mit dem Titel alle so zufrieden? Oder sollen wir nochmal drüber reden? (hatten es ja ursprünglich provisorisch dabei belassen)**
