### ISSUE TITLE
how to deal with no data available

### ISSUE THREAD

**Issue by herbertblb** [erictapen/mapping-migration#15]
Do we need to differentiate between cases where no data exists and cases where the case number is zero? and do we need to make this clear?

**Comment by erictapen** [comment]
One basic problem is that we can't know anything about a given COO (besides that it exists) before selecting it, as only in the moment of selection the API is queried (noticable by the delay).

From the top of my head there are the following possibilities of "no data":

1. API doesn't return countries (this should just be displayed as an error)
2. API doesn't return `asylum-decisions` for a given COO (this should just be displayed as an error)
3. `asylum-decisions` returns no european countries (e.g. an empty list)
4. `asylum-decisions` returns an european COA, that is empty
5. We don't have population data for a given COA
6. A year only consists of data on Cases or mixed data on Cases and Persons (depends on what we decide in #21)
7. We have a gap inbetween years, e.g. for `AFG->AUS` we have 2013 and 2015, but not 2014
8. We have year data for a COA, but the total of asylum decisions is 0.

**Comment by herbertblb** [comment]
to 6.: data on cases is still data, so at least for now we should include this as you did (and as I commented in #21) 
to 8.: Séra opened another issue #29 on cases where the data is zero

**Comment by erictapen** [comment]
With https://github.com/erictapen/mapping-migration/commit/03008d870fa247523666ce4460b62f381f38eadf, 3. and 4. should now be handled.

![tmp cJb2Y4sy1q](https://user-images.githubusercontent.com/11532355/149688569-3ecc09f1-8a7f-45af-a97e-327db56a2e6e.png)

**Comment by erictapen** [comment]
Regarding 7. we'll allow for the same year range (2000-today) for every country combination for the sake of consistency.
