### ISSUE TITLE
Differentiating between prima facie refugees, refugees and asylum seekers in the data set / visualization

### ISSUE THREAD

**Issue by seragarez** [erictapen/mapping-migration#16]
@martinedoesgis

If we understood correctly, seeking asylum is the precondition / first step in the process of officially being recognized as a refugee. According to the UNHCR website, in some cases of mass movements, people are granted the refugee status without having to apply for it (so called prima facie refugees). Are these numbers included in the number of refugees? Is there any way to distinguish prima facie refugees from refugees in the data set? This information is relevant to our project because until now, we only include data from the asylum decision data set. Refugees that get refugee status without applying for it thus will not appear in our visualization and distort the image of how many refugees a country acommodates (e.g. Pakistan: small numbers of applications and decisions, but huge numbers of Afghan refugees). Can we somehow include refugees without double counting those who got their asylum recognized after applying and therefore are already appear in the dataset on asylum decisions? Do you have any ideas of how we could solve this issue?

**Comment by herbertblb** [comment]
we are now focusing on Europe, where the difference between the numbers is not so big. So we just stay with the asylum decisions and do not include number of refugees.

**Comment by herbertblb** [comment]
answer by Léo:
 Is there any way to distinguish prima facie refugees from refugees in the data set? 
    No not in the stock figures – all those granted refugee status either by group (prima-facie) or individual recognition are included as refugees.
    You could differentiate these in the flow figures though.  We also are working on a flow dataset, and these will be included there too. 
    Would that be useful to send you the latest experimental draft dataset for now?

**Comment by herbertblb** [comment]
answer by Léo:
If we understood correctly, seeking asylum is the precondition / first step in the process of officially being recognized as a refugee. According to the UNHCR website, in some cases of mass movements, people are granted the refugee status without having to apply for it (so called prima facie refugees). Are these numbers included in the number of refugees?
 --Yes absolutely, these are included in the stock figures.  The flow figures, separating prima facie (also called group recognition) and individual recognition are also published in one of the annexes to the global trends report each year.  The latest annex tables are attached for e.g. 2020 – see tab 3.

**Comment by herbertblb** [comment]
answer by Léo:
Can we somehow include refugees without double counting those who got their asylum recognized after applying and therefore are already appear in the dataset on asylum decisions?

    --Yes – this is where the flow dataset is handy.  It includes asylum applications rather than decisions (as we want the most timely data), but you could combine the group recognitions from this dataset with the individual decisions from the asylum dataset.

**Comment by herbertblb** [comment]
I do not really know what stock and flow figures mean

**Comment by herbertblb** [comment]
here he gives us a possible solution to our problem. But this would probably change the app, is this worth it?

**Comment by herbertblb** [comment]
ask Léo: are we allowed to use the data from the excel sheet?
