### ISSUE TITLE
Merge decision level attributes on asylumDecisions

### ISSUE THREAD

**Issue by erictapen** [erictapen/mapping-migration#2]
Our current data display is incomplete. Actually there are always multiple entries per year, differentiated by the `dec_level` attribute.

We currently only display the first entry and we should merge all entries and display them together.

![tmp cKDzKEWd3T](https://user-images.githubusercontent.com/11532355/148085293-852644ac-ee59-40ec-a9c8-adaab730261e.png)

**Comment by erictapen** [comment]
Ich dachte erst ich wüsste was jetzt zu tun ist aber jetzt bin ich mir doch nicht mehr so sicher. Es ist ja so, wie von @seragarez in https://github.com/erictapen/mapping-migration/issues/24#issue-1096387895 beschrieben, dass immer nur eines von potenziell mehreren decision levels/types in unserem Interface angezeigt wird. Denn es ist ja so: Es gibt für *jedes* `dec_level` einen Datensatz, nicht nur für jedes Jahr wie ich zuerst annahm. Das wollen wir ja aber gar nicht anzeigen, oder?

Wäre es deswegen vielleicht das beste wenn wir `dec_level` komplett ignorieren und nur die Zahlen aufaddieren?

![tmp Sg2JhA7Mgp](https://user-images.githubusercontent.com/11532355/148580116-d605a6bd-039d-421f-826f-d20418c3a1b2.png)

Also im Falle von Eritrea wären das dann 2713 recognized, 182 CP, 99 rejected.

**Comment by seragarez** [comment]
Wir haben in der Kleingruppe gerade kurz drüber gesprochen, @erictapen, und ja wir glauben, dass wir dec_level komplett ignorieren und die Zahlen aufaddieren können, weil wir in unserer vis ja eh nicht zwischen den dec_levels unterscheiden! :)

**Comment by erictapen** [comment]
Nice, danke!

**Comment by erictapen** [comment]
So, das sollte jetzt gefixt sein! Ich habe bei der Gelegenheit gleich den application type und den procedure type aus dem Code gelöscht, da wir den ja gar nicht darstellen, oder?

Ab jetzt gilt also wieder: Alle diskrepanzen die ihr jetzt in den Daten findet sind neue Bugs! (Oder der alte und ich hab ihn doch nicht richtig gefixt).

@yellowkobra @Findus2000 @herbertblb @seragarez
