### ISSUE TITLE
 What does "Judicial Review" (JR) in the dataset on asylum decisions mean? 

### ISSUE THREAD

**Issue by seragarez** [erictapen/mapping-migration#20]
@martinedoesgis

What does "Judicial Review" (JR) in the dataset on asylum decisions mean? Does this also include the review of cases where asylum was recognized a few years prior and then has to be reviewed due to new circumstances?

**Comment by herbertblb** [comment]
answer by Léo:
--Exactly – see above in the explanation on the first instance decisions
