### ISSUE TITLE
Check focus on Europe as COA

### ISSUE THREAD

**Issue by seragarez** [erictapen/mapping-migration#23]
Check and compare the data for European countries as Country of Asylum. Do the countries only/mainly recognize refugees by way of asylum application? Are there interesting differences between the numbers recognized/rejected (also considering the population size of the respecting countries)? Could this be a focus for our project (in order to avoid the issue we have with including refugees that have not applied for asylum)?

**Comment by herbertblb** [comment]
We decided on a Europe focus. It will be explained in the introduction in the context of the strict regulation of migration movements and the trend to develop more and more categories, that it is not easy to become a refugee
