### ISSUE TITLE
Include First Instance Decisions (FI) in Web App

### ISSUE THREAD

**Issue by seragarez** [erictapen/mapping-migration#24]
Beim Beispiel Eritrea (COO) und Denmark (COA) zwischen 2015-2021 sind die First Instance Decisions (FI by Stage of Procedure; siehe hier https://www.unhcr.org/refugee-statistics/download/?url=T7YIxt) nicht drin. Weiß nicht, ob das auch bei anderen Ländern ein Problem ist, ich sag Bescheid falls ich noch was in die Richtung finde!

**Comment by seragarez** [comment]
Bzw ich habe das Gefühl dass teilweise nur die Administrative Review Decisions (AR unter Stage of Procedure) drin sind. So z.B. bei Eritrea-->Sweden

**Comment by erictapen** [comment]
Yes, danke, das ist ein Bug! Das gleiche Problem ist das, was in https://github.com/erictapen/mapping-migration/issues/2 beschrieben ist. Ich schließe dieses Issue mal, so dass wir das Problem in dem anderen weiter verfolgen können.
