### ISSUE TITLE
Imprint

### ISSUE THREAD

**Issue by erictapen** [erictapen/mapping-migration#25]
We need an imprint!

- Where we list our names?
- Where we mention our data sources

**Comment by seragarez** [comment]
Right now, we have a "Who We Are" and "Sources" written down below the Einleitung on Miro. Maybe we also need to add the FHP Logo and/or UNHCR Logo somewhere? Or should we create a new issue for Logos (which ones do we want/need and where should we place them?)?

**Comment by herbertblb** [comment]
John does not want to be mentioned by name, from Léo I did not hear back yet

**Comment by herbertblb** [comment]
@erictapen is there a link to the API? I don´t know how to reference it. If there is a link, could you post it here?

**Comment by erictapen** [comment]
Finally found some [Terms of Use](https://www.unhcr.org/terms-and-conditions-data.html) for data provided by UNHCR:

What stuck with me:

> 5. You may not publicly represent or otherwise assert or imply that UNHCR, in the past, currently or in the future, participates, sponsors, approves or endorsed the manner or purpose of your use or reproduction of the Datasets.

> 7. UNHCR name and emblem are the exclusive property of UNHCR. They are protected under international law. Unauthorized use is prohibited. They may not be copied or reproduced in any way without the prior written permission of UNHCR. You shall not represent or otherwise imply an association or affiliation with UNHCR without the prior written permission of UNHCR.

For referencing the API I'd use these two URLs Marian provided to us: https://api.unhcr.org/docs/refugee-statistics.html for API documentation and https://www.unhcr.org/refugee-statistics/download/ for broader information about what is possible with it.

**Comment by herbertblb** [comment]
So I guess we cannot say that they were our project partners unless we have their written permission, right? But we can say that we are using data provided or collected by the UNHCR accessible via the API?

**Comment by herbertblb** [comment]
I now sent Léo an email with a suggestion of wording

**Comment by herbertblb** [comment]
@erictapen we also need to reference where we get the numbers of inhabitants from. Could you set me up with a link?

**Comment by erictapen** [comment]
@herbertblb Good point! https://github.com/datasets/population

**Comment by herbertblb** [comment]
source code einbetten https://github.com/erictapen/mapping-migration
Vergangenheit
