### ISSUE TITLE
how to deal with data --> 0 (decisions < 1)?

### ISSUE THREAD

**Issue by seragarez** [erictapen/mapping-migration#29]
We decided to handle this issue separately from the one dealing with "no data available". Our suggestion would be that if decisions = 0 or < 1 the bar chart should be white. Right now, in these cases the bar chart either has one shade of grey or two, which does not make sense with the color coding and is confusing. What do you think @erictapen ?

**Comment by herbertblb** [comment]
![grafik](https://user-images.githubusercontent.com/97114845/149674899-d0d57764-e823-4971-8686-b3cc3648272f.png)
 
this is an example: 0 decisions in total, but percentages are angegeben which is confusing.

**Comment by erictapen** [comment]
I agree that it's confusing, but the percentage data should be correct and is therefore worth to show imho.

How about we display it as "Per 500,000 inhabitants there was less than one decision in total"?

Also note that the absolute numbers below will eventually be replaced by footsteps, so in this case there just would'nt be any footsteps displayed.

**Comment by herbertblb** [comment]
I agree it is info worth showing, but then we have to make clear to the user why there still are percentages shown

**Comment by herbertblb** [comment]
we agreed on the solution @erictapen suggested above: less than one decision in total

**Comment by erictapen** [comment]
Implemented in https://github.com/erictapen/mapping-migration/commit/c0c2b91b5a6addb47ea02ebf2bde9680d3e74b92 !
