### ISSUE TITLE
Einleitung und Learning

### ISSUE THREAD

**Issue by erictapen** [erictapen/mapping-migration#3]
Wir brauchen einen Einleitungstext, der den Besucher\*innen unserer Webseite das Projekt erklärt.

**Comment by seragarez** [comment]
Da sollte u.a. auch rein, dass wir nicht einbeziehen, wo es gar keine Asylanträge/-entscheidungen gab (Wert 0)

**Comment by herbertblb** [comment]
Comment Marian:
>i am missing a bit of handholding or on-boarding when visiting the visualization. why would explore this and what would i learn?

**Comment by erictapen** [comment]
Ich denke es wäre gut, wenn wir bis zur Präsentation einen Text haben, deswegen habe ich ihn mal in den Milestone hinzugefügt.

**Comment by seragarez** [comment]
@erictapen @herbertblb @yellowkobra @Findus2000 Einleitungstext ist auf dem Miro. Es gibt zwei Versionen, die wo Version 2 hintersteht ist die aktuellere. Es stehen schon ein paar Fragen dran, aber wäre cool, wenn ihr es euch alle nochmal durchlest und Verbesserungsvorschläge und Anmerkungen hinterlasst oder direkt im Text etwas ändert - also feel free da einfach direkt dran zu arbeiten! Ich weiß Stand jetzt nämlich außer von Kathi noch gar nicht, ob euch das von der Richtung, vom Wording/Stil und vom Inhalt her zusagt.

**Comment by erictapen** [comment]
Aus Zeitgründen implementiere ich die Einleitung erstmal so wie in @Findus2000 Skizze.

**Comment by erictapen** [comment]
So, die Einleitung ist jetzt in der Webapp.

Da ich ein paar kleine Formatierungsänderungen am Text machen musste wäre es gut, wenn wir ab jetzt alle Änderungen im Code machen! Kann ich bei Gelegenheit auch nochmal zeigen wie das geht, funktioniert recht easy über die Weboberfläche.

**Comment by herbertblb** [comment]
oh ja, das wäre interessant zu wissen! Also du meinst, wenn wir den text inhaltlich überarbeiten, dass wir das direkt im Code machen? @erictapen

**Comment by erictapen** [comment]
@herbertblb Ja genau das wäre mir am liebsten! Weil ich habe jetzt schon ein paar Änderungen dran gemacht, z.B. deutsche Anführungszeichen durch englische ersetzt oder absätze/überschriften in HTML definiert.

In der Datei [`src/Introduction.elm`](https://github.com/erictapen/mapping-migration/blob/main/src/Introduction.elm) ist der gesamte Text. Dann könnt ihr zum bearbeiten rechts oben auf das Stift Icon klicken. Am besten editiert ihr nur die Zeilen mit englischer Sprache, aber allgemein braucht Ihr euch überhaupt keine Sorgen machen dass ihr irgendwas kaputt macht. Also editiert gerne drauf los :grinning:

**Comment by herbertblb** [comment]
Wünsche von Kerstin:

- kürzer
- kürzere Absätze
- Zweiteilung: erster, kurzer Teil als Teaser, der Rest aufklappbar (vier, fünf Sätze am Anfang)

**Comment by herbertblb** [comment]
if animation is implemented: fit introduction (on Miro, I already wrote an alternative paragraph describing how the webapp works in the introduction text element)
