### ISSUE TITLE
Rechtschreibfehler: complementary

### ISSUE THREAD

**Issue by herbertblb** [erictapen/mapping-migration#30]
![grafik](https://user-images.githubusercontent.com/97114845/149735794-48567e88-a03b-440c-bee8-6e473d593799.png)

@erictapen If you find the time, could you fix this mistake? It has to be complementary, not complimentary.

**Comment by erictapen** [comment]
Fixed in 86e391043f6d722f7f6cfcba5cf5f114255a0868, thanks!
