### ISSUE TITLE
slider shows 2021 in the beginning 

### ISSUE THREAD

**Issue by herbertblb** [erictapen/mapping-migration#32]
![grafik](https://user-images.githubusercontent.com/97114845/149742899-4fded041-7b09-4d96-858c-3b1290b057da.png)

When the slider has not been moved and sits on the left, it shows 2021 instead of 2000. When it is moved, it shows the years where they are supposed to be

**Comment by erictapen** [comment]
Same problem with the COA selection here.

I can't really wrap my head around the problem, but for starters, I'll make it consistent:

- The COA2 is always the first element of the list.
- The year starts with 2000
