### ISSUE TITLE
earliest year available 2001 in some combinations

### ISSUE THREAD

**Issue by herbertblb** [erictapen/mapping-migration#33]
![grafik](https://user-images.githubusercontent.com/97114845/149743327-f1e1d4da-dccf-4f06-9756-6b189db2c780.png)

with some country combinations, the earliest year selectable is 2001 instead of 2000. Why is that? Relation to #15 ?

**Comment by erictapen** [comment]
We'll fix this as described in https://github.com/erictapen/mapping-migration/issues/15#issuecomment-1014308524
