### ISSUE TITLE
footprints are cut off

### ISSUE THREAD

**Issue by herbertblb** [erictapen/mapping-migration#35]
![grafik](https://user-images.githubusercontent.com/97114845/149924270-caad4d62-0f85-411a-b55b-7d305096109b.png)

The lowest footprints are cut of. Is this deliberately?

**Comment by erictapen** [comment]
Mh nope, this looks like a layout error.

Could you post a screenshot of the whole screen? I have the suspicion that your bar rectangles have less height than mine.

![tmp sGT7ytANz8](https://user-images.githubusercontent.com/11532355/149930907-0a8a86e0-87d6-4f32-9e5e-d54e17e3676d.png)

**Comment by erictapen** [comment]
I just fixed a bug where the footprints in even columns (read from left to right) could drop below the border of the frame. Could you recheck, @herbertblb ?

**Comment by herbertblb** [comment]
![grafik](https://user-images.githubusercontent.com/97114845/150776692-0732cc58-21af-4e1d-ae62-cdf88118aea2.png)
 found something else: footprints cut off to the right

**Comment by herbertblb** [comment]
oh and also still at the bottom!

**Comment by herbertblb** [comment]
![grafik](https://user-images.githubusercontent.com/97114845/150776851-0343f57d-f88e-48be-9052-2c05e61c1d68.png)
this is the full screenshot

**Comment by erictapen** [comment]
Thanks @herbertblb! Will take a look at it tomorrow.
Unfortunately there is the general problem that sometimes there isn't enough space to display all the footprints.

**Comment by herbertblb** [comment]
![grafik](https://user-images.githubusercontent.com/97114845/154108400-eca6a47d-5950-42c8-898f-2144c183eebb.png)

not cut off anymore, but the footprints exceed the size of the bar chart
