### ISSUE TITLE
implement explanation for footprints

### ISSUE THREAD

**Issue by herbertblb** [erictapen/mapping-migration#37]
explain: 1 set of footprint equals 1 person per 500,000 inhabitants

**Comment by erictapen** [comment]
I implemented this in a basic way. Also allowed myself to shorten the description text. Are you ok with that, @herbertblb ?
![tmp iJsbGhHFrM](https://user-images.githubusercontent.com/11532355/152571243-cc9adffc-39e6-47ca-80cb-89330a321dc8.png)
