### ISSUE TITLE
Implement infobox about decisions

### ISSUE THREAD

**Issue by seragarez** [erictapen/mapping-migration#38]
Since Leo explained that several decisions can be made concerning one person in a year (and therefore decision numbers does not equal number of persons!), Kathi and I think that should be explained somehow in the vis. Maybe through an "i"-info-Button in the legend? That explanation could also include the information that data are sometimes counted as cases.

**Comment by herbertblb** [comment]
- Text verfassen
- Ort finden, wo dieser erscheinen soll
- implementieren

**Comment by herbertblb** [comment]
see #21

**Comment by erictapen** [comment]
We want to add an infobox near the footprint legend explaining what a "decision" really is. Also we remove the cases/person information per country altogether, as it is not that interesting.

**Comment by herbertblb** [comment]
Kathi will try to put the text directly into the code.

**Comment by erictapen** [comment]
@herbertblb I just added five strings for every infobox in the code in 305608f941c9460c1cd7edec0d60c0204292ebf1.
If you search for `explanation for` in `src/Main.elm`, you'll find all five placeholders.

**Comment by herbertblb** [comment]
Rundungsfehler hier thematisieren?
"Only values above one per category are displayed as a footprint"

**Comment by erictapen** [comment]
> Rundungsfehler hier thematisieren? "Only values above one per category are displayed as a footprint"

Das würde so nur zutreffen wenn ich keine mathematische Lösung für #46 finde! Ansonsten könnte auch ein Wert von 0.8 unter Umständen zu einem Footprint führen.
