### ISSUE TITLE
for Aruba, it´s not possibe to select COAs

### ISSUE THREAD

**Issue by herbertblb** [erictapen/mapping-migration#44]
![grafik](https://user-images.githubusercontent.com/97114845/154999412-7cc67010-bb6b-44a6-b7f5-ee788dceb842.png)

when Aruba is selected as COO, which is default state right now, I cannot select countries of asylum

**Comment by erictapen** [comment]
Thanks, yeah that's still a problem. I just fixed a bug that AFG is actually set as the default COO 01d1ae433cc0356700f63c9fb3cb4fc02608b0c1, so this isn't visible per default at least.

**Comment by erictapen** [comment]
Fixed, the URL still looks weird though. UKN stands for "Unknown Country", I'd like to get rid of that eventually.

![tmp alCHPCi0ed](https://user-images.githubusercontent.com/11532355/155004184-5edcf9ad-fb18-4c33-bb16-32c6302e9956.png)
