### ISSUE TITLE
Einzug links

### ISSUE THREAD

**Issue by herbertblb** [erictapen/mapping-migration#45]
![grafik](https://user-images.githubusercontent.com/97114845/155099984-d6f6045b-7415-49d0-9281-9f3ad90c9d24.png)

In my opinion (or on my screen in Firefox) the text is too far to the left, it starts directly at the edge of the screen. Is this something I could fix in the introduction.elm or does this have to do with the general layout and therefore in the main.elm?

**Comment by erictapen** [comment]
Mh you could try to add styling to the documentation. Every HTML element like div, p, h1 etc has two lists as arguments:

```elm
div [] [ text "Text" ]
```

In the first list you can add styling information for the element, which is written in CSS:

```elm
div [ style "margin-left: 3em;" ] [ text "Text" ]
```

`em` is a distance unit like `cm`, that is dependent on the font size of the website.

If you add `margin-left` to the outermost `div`, you should get the desired effect.
