### ISSUE TITLE
Legend for COO/COA selection

### ISSUE THREAD

**Issue by erictapen** [erictapen/mapping-migration#49]
As with the new drop-down menus we don't have a legend anymore that explains what can be selectod.

Wouly anyone mind to make a sketch of how to solve this problem? Unfortunately we cannot write "country of asylum" directly in the selection, as we always provide a preselected set of countries.

![tmp 9hCN4Gy04F](https://user-images.githubusercontent.com/11532355/155401330-b41343d8-cfd4-461a-82b1-cd264b664b23.png)

**Comment by erictapen** [comment]
Reminder: This was how it looked before I started to use the new select elements.

![tmp 7la9gdTlGy](https://user-images.githubusercontent.com/11532355/155402342-066b2930-6367-4cde-9e47-b905092e3280.png)

**Comment by seragarez** [comment]
Hab eben mal ein Bisschen rumprobiert und bin bei dieser sehr simplen Variante gelandet. Alles andere war mir irgendwie zu kastenförmig und mit den Balken haben wir irgendwie schon so viel rechteckige Formen. Hab die Schrift auch mal rechtsbündig gesetzt zur Abwechslung und ich finde es macht auch Sinn, weil dann die "Aufforderung" quasi über dem Drop-Down-Pfeil ist. Also ja, nichts besonderes aber vielleicht hilft es ja trotzdem :

![webapp_legend for coo-coa selection](https://user-images.githubusercontent.com/97115079/155427231-f4d32fcf-762f-4fb9-8e76-9eec36cf1edc.jpg)
)

**Comment by seragarez** [comment]
Kathi schlug gerade vor, die Linien in einem Grauton zu machen statt schwarz, nur so als Vorschlag :)

**Comment by erictapen** [comment]
Ist implementiert, danke nochmal für die Skizze!
