### ISSUE TITLE
title in decision category infoboxes

### ISSUE THREAD

**Issue by herbertblb** [erictapen/mapping-migration#50]

**Comment by erictapen** [comment]
I'll implement that barElement accepts an `Html Msg` instead of `String` for the explanation.

**Comment by erictapen** [comment]
Hey Kathi, ich hab dir in 7aa408195be5e94a1a83312fe99e53fce92a97d7 das eingebaut, so dass du an den gewohnten Stellen jetzt (elm-)HTML schreiben kannst. Hab den bisherigen Text durch ein einfaches `[ text "alter text" ]` ersetzt, also `List (Html Msg)` ersetzt.

`h1` in den Infoboxen wird jetzt ungestyled halt riesig aussehen. Deswegen habe ich dir in 9b49d5f6a9bdfea3f305c5c54509b8dd8104ec71 noch das Styling aus der infobox zu den Fußstapfen unter `infoboxH1Style` abstrahiert. Das kannst du so anwenden:

```elm
h1 [ infoboxH1Style ] [ text "überschrift" ]
```

**Comment by herbertblb** [comment]
I now added titles to the infoboxes. Please edit them or text me if you want them to be different.
