### ISSUE TITLE
Texte in Blocksatz

### ISSUE THREAD

**Issue by herbertblb** [erictapen/mapping-migration#52]
try out: Einleitungstexte in Blocksatz

**Comment by erictapen** [comment]
The corresponding CSS property is `text-align: justify;`: https://developer.mozilla.org/en-US/docs/Web/CSS/text-align

I'm skeptical of Blocksatz though, usually it makes things worse imho.

**Comment by herbertblb** [comment]
Entscheidung: Blocksatz wieder rausnehmen
