### ISSUE TITLE
Visually separate definitions "asylum seeker" and "refugee" from rest 

### ISSUE THREAD

**Issue by herbertblb** [erictapen/mapping-migration#53]
We want the definitions of asylum seeker and refugee to be next to each other, not below each other. A possibility would be to work with boxes / frames.

**Comment by herbertblb** [comment]
Ideen: 

- Titel oder Text einrücken
- Titel kursiv

**Comment by herbertblb** [comment]
Abstand gleich unter "refugee" definition und über "asylum" definition

**Comment by erictapen** [comment]
How about this?
![tmp wdCwCfrG0U](https://user-images.githubusercontent.com/11532355/155893390-f462d758-3652-4d1e-a734-16eb3a3db5ef.png)
