### ISSUE TITLE
implement "read introduction" button to get back to introduction once user is on the website

### ISSUE THREAD

**Issue by herbertblb** [erictapen/mapping-migration#54]
When the introduction is closed and the legend is visible, we need a button that reopens the introduction.

**Comment by seragarez** [comment]
Wäre es möglich, den Button etwas höher zu setzen? Auf meinem Bildschirm sieht man ihn nämlich nicht, ohne runterzuscrollen.. Weiß, dass es platztechnisch gerade schwierig ist, aber fänd es auch doof, wenn Menschen oder Marian dann den Button nicht sehen.
![grafik](https://user-images.githubusercontent.com/97115079/155967581-14a0681b-eeec-46a6-8910-a12d8acd0936.png)

**Comment by erictapen** [comment]
Auf jeden Fall! Ich bin tatsächlich mit dem ganzen Areal unterhalb der Select menus noch nicht zufrieden und werd das noch ein bisschen anordnen müssen. Hab das aber auf dem Schirm und würde dieses Issue deswegen erstmal wieder schließen.

![tmp 3KK9eEDUkV](https://user-images.githubusercontent.com/11532355/155990230-4da9c5cd-56d7-4e04-93e6-52b7f0269999.png)
