### ISSUE TITLE
Use quotation marks, dash and apostrophe in text

### ISSUE THREAD

**Issue by erictapen** [erictapen/mapping-migration#64]
Correct quotation marks: `“”` https://en.wikipedia.org/wiki/Quotation_mark
Correct dash (most of the time): `–`
Correct apostrophe: `’` https://en.wikipedia.org/wiki/Apostrophe#Unicode

**Comment by seragarez** [comment]
Hab's gerade geändert und committed. Hoffe ich habe nichts übersehen :)

**Comment by seragarez** [comment]
Sollte alles richtig sein, wenn Code/Seite aktualisiert wird
