### ISSUE TITLE
Title for missing migrants infobox

### ISSUE THREAD

**Issue by erictapen** [erictapen/mapping-migration#69]
I think we should provide a bit more context to the Missing Migrants infobox. Currently the title is just "Missing Migrant", which doesn't really provide the user with much information on why we included this curiously mis-aligned infobox on top of everything else.

![tmp BajHfKmITy](https://user-images.githubusercontent.com/11532355/156005130-b26b3c5d-9179-45b1-873e-e547ccff9c46.png)

Maybe we could change the title to something along the lines of "Not all people on the move can be accounted here. Read here about migrants that go missing" etc.?

**Comment by herbertblb** [comment]
Stimmt, die Begründung fehlt etwas. Gute Idee

**Comment by seragarez** [comment]
Vielleich so? "Not all migrants who try to make their way to or through Europe arrive safely. That is why some never get to apply for asylum in the first place and therefore cannot be accounted for here."
Und dann den Untertext?

**Comment by seragarez** [comment]
Hab's committed!

**Comment by erictapen** [comment]
Und deployed. Top!
