### ISSUE TITLE
Missing migrants

### ISSUE THREAD

**Issue by herbertblb** [erictapen/mapping-migration#7]
We do not have exact numbers on missing migrants. How can we include these insecurities? Problem: footprints are coded to be 1 person, if we use footprints for missing people, we suggest exact numbers

**Comment by seragarez** [comment]
You can find the proposal Kathi and I worked on today for the animation and missing migrants in the "Animation" frame on Miro!

**Comment by seragarez** [comment]
Should missing migrants only appear when whole page is reloaded? Or can we make it appear more often (e.g. when chosing a new COO, COA or both)?

**Comment by seragarez** [comment]
Text for the Missing Migrants infobox:

In Europe and the Meditteranean sea, the Missing Migrant Project has recorded 24,278 deaths and disappearances of migrants from 2014 until the end of February 2022. The estimated number supposedly is very much higher. For more information, please click here: https://missingmigrants.iom.int/.

**Comment by herbertblb** [comment]
I commited the above text to the code

**Comment by erictapen** [comment]
Thanks, is deployed!
