### ISSUE TITLE
Allow for selection of multiple COAs

### ISSUE THREAD

**Issue by erictapen** [erictapen/mapping-migration#8]

**Comment by erictapen** [comment]
I just started implementing this and then stumbled on some questions I'd rather have an answer for before continuing.

1. Do we want to have an amount of COAs selectable that is different from 2? E.g. None, 1 or 5?
2. If yes, is it ok if there is some "default" selection as it currently is the case, e.g. the first country in the list or the first two?

I think this doesn't just concern the design, so I'm pinging you all. @Findus2000 @yellowkobra @herbertblb @seragarez

**Comment by herbertblb** [comment]
@erictapen 
to 1: we agreed on 2 countries, so we should stay with that I guess? maybe we could consider enabling selecting more countries in next steps after the presentation
to 2: I don´t have a strong opinion on that

**Comment by seragarez** [comment]
Hm that's a good question. But regarding 1. I would suggest we stick with the two as well, at least for now!
And for 2: I think it would be more elegant without a "default" selection, but that's definitely a "nice to have" we can ignore. So just do what's easier for you!

**Comment by erictapen** [comment]
Implemented selection of two COAs in c20dee44edecd47ef24e309a4bf86c638250a3e9!

The implementation commits currently to a fixed number of two COAs, so changing that could get a bit of work. Was easier that way.
